     
# Enable H2 Console
spring:
 # h2:
  #  console:
   #   enabled: true
  

              
  datasource:
    url: jdbc:mysql://[YOU_HOST]:3306/[YOUT_DB_NAME]?createDatabaseIfNotExist=true&serverTimeZone=UTC&sslMode=DISABLED
    username: [YOU_USERNAME]
    password: [YOU_PASSWORD]
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
  jmx:
    enabled: false
     
          
logging:
  level:
    org.hibernate.sql: debug 
