     
# Enable H2 Console
spring:
 # h2:
  #  console:
   #   enabled: true
  

              
  datasource:
    url: jdbc:mysql://localhost:3306/faturacaodb?createDatabaseIfNotExist=true&serverTimeZone=UTC&sslMode=DISABLED
    username: develloper
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
  jmx:
    enabled: false
     
          
logging:
  level:
    org.hibernate.sql: debug 